### ISSUE TITLE
不兼容4.2.2

### ISSUE THREAD

**Issue by dopost** [zhibuyu/KeyStoreEncryDemo#1]
java.lang.NullPointerException
02-09 18:13:42.014 20502-20502/com.panda.test W/System.err:     at com.panda.test.EncryUtils.encryptString(EncryUtils.java:102)
02-09 18:13:42.014 20502-20502/com.panda.test W/System.err:     at com.panda.test.MainActivity.lambda$onCreate$0(MainActivity.java:54)
02-09 18:13:42.014 20502-20502/com.panda.test W/System.err:     at com.panda.test.MainActivity.access$lambda$0(MainActivity.java)
02-09 18:13:42.014 20502-20502/com.panda.test W/System.err:     at com.panda.test.MainActivity$$Lambda$1.onClick(Unknown Source)
02-09 18:13:42.014 20502-20502/com.panda.test W/System.err:     at android.view.View.performClick(View.java:4204)
02-09 18:13:42.014 20502-20502/com.panda.test W/System.err:     at android.view.View$PerformClick.run(View.java:17355)
02-09 18:13:42.014 20502-20502/com.panda.test W/System.err:     at android.os.Handler.handleCallback(Handler.java:725)
02-09 18:13:42.014 20502-20502/com.panda.test W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:92)
02-09 18:13:42.014 20502-20502/com.panda.test W/System.err:     at android.os.Looper.loop(Looper.java:137)
02-09 18:13:42.014 20502-20502/com.panda.test W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5069)
02-09 18:13:42.014 20502-20502/com.panda.test W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
02-09 18:13:42.014 20502-20502/com.panda.test W/System.err:     at java.lang.reflect.Method.invoke(Method.java:511)
02-09 18:13:42.014 20502-20502/com.panda.test W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
02-09 18:13:42.014 20502-20502/com.panda.test W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
02-09 18:13:42.014 20502-20502/com.panda.test W/System.err:     at dalvik.system.NativeStart.main(Native Method)

**Comment by zhibuyu** [comment]
你代码里EncryUtils这个类的102行报错，但我的代码102行是注释了的，你再看下你的代码
`      String encryptStr="";
            byte [] vals=null;
            try {
                KeyStore.PrivateKeyEntry privateKeyEntry = (KeyStore.PrivateKeyEntry)keyStore.getEntry(alias, null);
//            RSAPublicKey publicKey = (RSAPublicKey) privateKeyEntry.getCertificate().getPublicKey();
                if(needEncryptWord.isEmpty()) {
//                Toast.makeText(this, "Enter text in the 'Initial Text' widget", Toast.LENGTH_LONG).show();
                    return encryptStr;
                }

//            Cipher inCipher = Cipher.getInstance("RSA/ECB/PKCS1Padding", "AndroidOpenSSL");
                Cipher inCipher = Cipher.getInstance("RSA/ECB/PKCS1Padding");
//            inCipher.init(Cipher.ENCRYPT_MODE, publicKey);
                inCipher.init(Cipher.ENCRYPT_MODE, privateKeyEntry.getCertificate().getPublicKey());

                ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
                CipherOutputStream cipherOutputStream = new CipherOutputStream(
                        outputStream, inCipher);
                cipherOutputStream.write(needEncryptWord.getBytes("UTF-8"));
                cipherOutputStream.close();

                vals = outputStream.toByteArray();
            } catch (Exception e) {
                e.printStackTrace();
            }`
